### PR TITLE
[Swift] Add option to create structs instead of classes

### PR DESCRIPTION
**Pull request by thomasameisel**
Add the `struct` option which will generate structs instead of classes in Swift code

### CODE REVIEW

**Comment by thomasameisel** [comment]
@jbflanigan / @kivarsha do you mind generating the executable when you get a chance? No rush!

**Comment by kivarsha** [comment]
@thomasameisel sure thing. Do you want me to add it to this branch?

**Comment by thomasameisel** [comment]
@kivarsha yep thanks!

**Comment by kivarsha** [comment]
@thomasameisel done!

**Pull request merged**
